### ISSUE TITLE
Unhandled rejection TypeError when validating resources

### ISSUE THREAD

**Issue by richhall** [okfn/datapackagist#170] opened 2015-10-11 11:21 UTC
Using this example:
http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2Fa3e534c7f63911c22082%2Fraw%2Fc758f90a07804ffe23ca2f97b8fe696f71106d7f%2Fopendata_cambridgeshireinsight_org_uk_CORS.json

when I subsequently click on "Validate Resources" nothing happens and Chrome reports Unhandled rejection TypeError:
![image](https://cloud.githubusercontent.com/assets/1749835/10416521/67b4c636-7012-11e5-8cc8-adb8d1d05f6f.png)

```
Unhandled rejection TypeError: Cannot read property 'getValue' of undefined
    at Class.<anonymous> (http://datapackagist.okfnlabs.org/app.min.js:744:67)
    at tryCatcher (http://datapackagist.okfnlabs.org/vendor.min.js:4527:23)
    at Promise.module.exports.Promise._resolveFromResolver (http://datapackagist.okfnlabs.org/vendor.min.js:2624:31)
    at new Promise (http://datapackagist.okfnlabs.org/vendor.min.js:2217:37)
    at Class.jsonEditor.JSONEditorView.defaults.editors.resources.JSONEditor.defaults.editors.array.extend.getDataSource (http://datapackagist.okfnlabs.org/app.min.js:733:12)
    at http://datapackagist.okfnlabs.org/app.min.js:984:106
    at tryCatcher (http://datapackagist.okfnlabs.org/vendor.min.js:4527:23)
    at ReductionPromiseArray.module.exports.ReductionPromiseArray._promiseFulfilled (http://datapackagist.okfnlabs.org/vendor.min.js:3801:38)
    at ReductionPromiseArray.init (http://datapackagist.okfnlabs.org/vendor.min.js:2993:18)
    at ReductionPromiseArray.init (http://datapackagist.okfnlabs.org/vendor.min.js:3738:10)
    at Async._drainQueue (http://datapackagist.okfnlabs.org/vendor.min.js:152:12)
    at Async._drainQueues (http://datapackagist.okfnlabs.org/vendor.min.js:157:10)
    at drainQueues (http://datapackagist.okfnlabs.org/vendor.min.js:39:14)
```

**Comment by pwalsh** [comment] 2015-10-11 11:22
@gvidon pls check.

**Comment by gvidon** [comment] 2015-10-12 19:57
@pwalsh @richhall this https://github.com/okfn/datapackagist/pull/172 fixes the errors show in console, but it is still impossible to run validation of the example above. The problem is that app hangs on large CSVs. Should be fixed there https://github.com/okfn/datapackagist/issues/171

**Closed** 2015-10-13 06:01 UTC
